FROM tleyden5iwx/ubuntu-cuda


# Add dependencies.
COPY . /tmp
WORKDIR /tmp
#RUN conda env create -f environmenttf2gpu.yml

RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-5.3.0-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

# Run Jupyter
CMD tail -f /dev/null
