name: base_install
dependencies:
 - jupyterlab
 - Keras
 - matplotlib
 - mysql-connector-python
 - mysqlclient
 - numpy
 - pandas
 - PyMySQL
 - pyodbc
 - scikit-learn
 - scipy
 - seaborn
 - SQLAlchemy
 - statsmodels
 - tensorboard
 - urllib3